packages:
  - '.'          # The root itself
  - 'server'     # Your backend logic
  - 'shared'     # Shared types and schemas
  - 'mobile'     # Future mobile app
  - 'apps/*'     # Any future sub-apps
