20:49:41.211 Running build in Washington, D.C., USA (East) – iad1
20:49:41.212 Build machine configuration: 4 cores, 8 GB
20:49:41.330 Cloning github.com/myhuemungusD/skatehubba1 (Branch: feature/play-skate-polish-e2e, Commit: 2948b60)
20:49:42.675 Cloning completed: 1.345s
20:49:42.855 Restored build cache from previous deployment (CewRAHW2tVCXwhJnvycimkbtrDsV)
20:49:43.280 Running "vercel build"
20:49:44.130 Vercel CLI 50.3.1
20:49:44.708 Detected `pnpm-lock.yaml` version 9 generated by pnpm@10.x with package.json#packageManager pnpm@10.0.0
20:49:44.708 Running "install" command: `corepack enable && corepack prepare pnpm@10.0.0 --activate && pnpm -v && pnpm install --frozen-lockfile`...
20:49:44.879 Preparing pnpm@10.0.0 for immediate activation...
20:49:47.771 10.0.0
20:49:48.656 Scope: all 4 workspace projects
20:49:50.430 
20:49:50.593 Done in 2.4s
20:49:51.642 Scope: all 4 workspace projects
20:49:51.647 Already up to date
20:49:51.647 Done in 477ms
20:49:52.529 
20:49:52.529 > skatehubba-client@1.0.0 build /vercel/path0/client
20:49:52.529 > pnpm run typecheck && vite build
20:49:52.529 
20:49:52.986 
20:49:52.986 > skatehubba-client@1.0.0 typecheck /vercel/path0/client
20:49:52.986 > tsc --noEmit
20:49:52.986 
20:50:05.122 src/context/AuthProvider.tsx(57,10): error TS2305: Module '"../lib/firebase/config"' has no exported member 'auth'.
20:50:05.122 src/context/AuthProvider.tsx(57,27): error TS2305: Module '"../lib/firebase/config"' has no exported member 'db'.
20:50:05.123 src/hooks/useUserRoles.ts(12,10): error TS2305: Module '"../lib/firebase/config"' has no exported member 'functions'.
20:50:05.123 src/lib/firebase.ts(14,3): error TS2305: Module '"./firebase/config"' has no exported member 'app'.
20:50:05.123 src/lib/firebase.ts(15,3): error TS2305: Module '"./firebase/config"' has no exported member 'auth'.
20:50:05.123 src/lib/firebase.ts(16,3): error TS2305: Module '"./firebase/config"' has no exported member 'db'.
20:50:05.123 src/lib/firebase.ts(17,3): error TS2305: Module '"./firebase/config"' has no exported member 'functions'.
20:50:05.123 src/lib/firebase.ts(18,3): error TS2305: Module '"./firebase/config"' has no exported member 'isFirebaseInitialized'.
20:50:05.123 src/lib/firebase/auth.service.ts(32,10): error TS2305: Module '"./config"' has no exported member 'auth'.
20:50:05.123 src/lib/firebase/index.ts(11,10): error TS2305: Module '"./config"' has no exported member 'app'.
20:50:05.124 src/lib/firebase/index.ts(11,15): error TS2305: Module '"./config"' has no exported member 'auth'.
20:50:05.124 src/lib/firebase/index.ts(11,21): error TS2305: Module '"./config"' has no exported member 'db'.
20:50:05.124 src/lib/firebase/index.ts(11,25): error TS2305: Module '"./config"' has no exported member 'isFirebaseInitialized'.
20:50:05.124 src/lib/firebase/profile.service.ts(18,10): error TS2305: Module '"./config"' has no exported member 'db'.
20:50:05.159  ELIFECYCLE  Command failed with exit code 2.
20:50:05.172  ELIFECYCLE  Command failed with exit code 2.
20:50:05.194 Error: Command "pnpm install && pnpm run build" exited with 2
